version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  service:
    hostname: go-mongo
    container_name: go-mongo
    build:
      context: .
    depends_on:
      - mongodb
    environment:
      MONGO_DB_NAME: gomongo
      MONGO_CONNECTION_URI: mongodb://root:example@mongodb:27017
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://go-mongo:8080/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
