version: "3"
services:
  service:
    hostname: go-mongo
    container_name: go-mongo
    build:
      context: .
    environment:
      MY_ENV: local-docker
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://go-mongo:8080/ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
